### PR TITLE
DEVOPS-946 Add workflow api-lint

### PR DESCRIPTION
**Pull request by dcrossleyau**

### CODE REVIEW

**Comment by MikeTaylor** [comment]
It's a side-point, but I am never comfortable with `trim_trailing_whitespace = true` in the editor configuration, given the significance of trailing whitespace in Markdown.

**Comment by MikeTaylor** [comment]
Thanks for catching the capitalization typo in the RAML. It makes me feel confident that there aren't other in there, or you would have caught those too!

**Comment by MikeTaylor** [comment]
The actual workflow seems to be just fine, but of course since it doesn't generate any output it's not especially spectacular. I expect `api-doc` is to follow?

**Review by MikeTaylor — APPROVED** [review]
Anyway, this is a good step!

**Comment by dcrossleyau** [comment]
Oh, that .editorconfig was intended to be in the workflows directory.

I would usually check that no Markdown file was using that method before adding that editorconfig at a higher level directory.

We had previously discussed that Markdown problem, and arrived at this solution:
https://dev.folio.org/faqs/how-to-use-editorconfig/#markdown-line-break

**Comment by dcrossleyau** [comment]
As said at DEVOPS-946, the api-doc workflow will be developed at mod-harvester-admin first.

**Comment by dcrossleyau** [comment]
The report from api-lint is in that step of the workflow run output. If there were errors, then they would be listed there.

**Comment by dcrossleyau** [comment]
Regarding the "typo". No, that was me testing a commit that would trigger that workflow, as it is restricted to changes in the "ramls" directory.

**Comment by MikeTaylor** [comment]
Thanks, David, that all sounds fine.

**Pull request merged**
